const {chromium}=require('playwright');const fs=require('fs'),crypto=require('crypto');
const root='reference-nsnn';fs.mkdirSync(root+'/api',{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}});const manifest={},tasks=[],states=[];p.on('response',r=>{if(!new URL(r.url()).pathname.startsWith('/api/'))return;tasks.push((async()=>{try{const u=new URL(r.url()),key=u.pathname+u.search,body=await r.body();const file=crypto.createHash('sha256').update(key).digest('hex').slice(0,16)+'.json';fs.writeFileSync(root+'/api/'+file,body);manifest[key]={file,status:r.status(),bytes:body.length};fs.writeFileSync(root+'/api/manifest.json',JSON.stringify(manifest,null,2))}catch{}})())});p.on('pageerror',e=>console.log('PAGEERROR',e.message));
async function ready(){await p.waitForTimeout(600);await p.waitForFunction(()=>!document.body.innerText.includes('Đang tải'),null,{timeout:20000}).catch(()=>{});await p.waitForTimeout(500);await p.mouse.move(0,0)}
async function snap(name){await ready();const data=await p.evaluate(()=>({url:location.href,text:document.body.innerText,selects:[...document.querySelectorAll('select')].map(e=>({label:e.labels?.[0]?.innerText.split('\n')[0]||e.getAttribute('aria-label'),value:e.value,disabled:e.disabled,options:[...e.options].map(o=>({label:o.text,value:o.value}))})),buttons:[...document.querySelectorAll('button')].map(e=>({text:e.innerText,aria:e.getAttribute('aria-label'),disabled:e.disabled})),headings:[...document.querySelectorAll('h2')].map(e=>e.innerText),viewport:{width:innerWidth,scroll:document.documentElement.scrollWidth},styles:{bodyFont:getComputedStyle(document.body).fontFamily,rootTokens:Object.fromEntries(['--bg','--card','--line','--ink','--muted','--data-main','--data-sub','--data-sub-bg','--up','--down','--m1','--m2','--m3','--m4','--m5','--nodata'].map(x=>[x,getComputedStyle(document.documentElement).getPropertyValue(x)]))}}));fs.writeFileSync(root+'/states/'+name+'.json',JSON.stringify(data,null,2));await p.screenshot({path:root+'/screenshots/'+name+'.png',fullPage:true});states.push({name,url:data.url,headings:data.headings});fs.writeFileSync(root+'/states/index.json',JSON.stringify(states,null,2));console.log('SAVED',name,data.url)}
async function go(q,n){await p.goto('https://dev-nsnn.thehegeo.com/'+q);await snap(n)}
await go('?year=2026&acc=PERIOD&item=tong-so&tab=overview','01-overview');
await p.locator('select').nth(1).selectOption('2');await snap('02-quarter2');await p.locator('select').nth(2).selectOption('5');await snap('03-quarter2-month5');await p.locator('select').nth(3).selectOption('YTD');await snap('04-month5-ytd');await p.locator('select').nth(4).selectOption({label:'THU NGÂN SÁCH NHÀ NƯỚC'});await snap('05-item-thu-nsnn');await p.locator('select').nth(4).selectOption({label:'TỔNG SỐ (trừ hoàn thuế GTGT)'});await snap('06-item-net-total');
await go('?year=2026&month=8&acc=PERIOD&item=tong-so&tab=overview','07-aug-overview');await p.locator('.cursor-zoom-in').first().click();await snap('08-trend-modal');await p.getByRole('button',{name:'Đóng',exact:true}).click();await p.getByRole('button',{name:'Theo tăng trưởng %',exact:true}).click();await snap('09-ranking-growth');await p.getByRole('button',{name:'Theo độ ổn định',exact:true}).click();await snap('10-ranking-stability');await p.locator('div.cursor-pointer').filter({has:p.locator('svg[width="220"]')}).first().click();await snap('11-ranking-modal');await p.keyboard.press('Escape');await p.getByRole('button',{name:'Sắc thuế',exact:true}).click();await snap('12-tax-composition');
await go('?year=2024&acc=PERIOD&item=tong-so&tab=detail','13-historical-2024');await p.locator('select').nth(5).selectOption({label:'Quận Hoàn Kiếm'});await snap('14-historical-district');await p.locator('select').nth(0).selectOption('2025');await snap('15-mixed-2025');await p.locator('select').nth(2).selectOption('6');await snap('16-june2025');await p.locator('select').nth(2).selectOption('7');await snap('17-july2025');await p.locator('select').nth(5).selectOption({label:'Hoàn Kiếm'});await snap('18-detail-ward');
await go('?year=2026&month=12&acc=PERIOD&item=tong-so&tab=overview','19-no-data');await go('?year=2026&month=8&quarter=1&acc=no&item=unknown&ward=unknown&tab=oops&foo=bar','20-invalid-url');await p.getByRole('button',{name:'Đóng cảnh báo'}).click();await snap('21-dismiss-notice');
await go('?year=2026&acc=PERIOD&item=tong-so&tab=compare','22-compare-empty');await p.getByLabel('Chọn phường/xã',{exact:true}).selectOption({label:'Hoàn Kiếm'});await snap('23-compare-default');await p.getByLabel('Kỳ A — kỳ trong năm',{exact:true}).selectOption('m8');await p.getByLabel('Kỳ B — kỳ trong năm',{exact:true}).selectOption('m8');await snap('24-compare-draft');await p.getByRole('button',{name:'So sánh',exact:true}).click();await snap('25-compare-aug');await p.locator('select').nth(0).selectOption('YTD');await snap('26-compare-ytd');await p.getByLabel('Kỳ A — kỳ trong năm',{exact:true}).selectOption('q3');await p.getByLabel('Kỳ B — kỳ trong năm',{exact:true}).selectOption('q3');await p.getByRole('button',{name:'So sánh',exact:true}).click();await snap('27-compare-q3');
await go('?year=2026&month=8&acc=PERIOD&item=tong-so&ward=hoan-kiem&tab=detail','28-detail-hoankiem');await p.locator('button').filter({hasText:/^Reset zoom$/}).click();await snap('29-reset-zoom');await p.getByRole('button',{name:'Tải lại dữ liệu',exact:true}).click();await snap('30-refresh');
await Promise.allSettled(tasks);fs.writeFileSync(root+'/api/manifest.json',JSON.stringify(manifest,null,2));fs.writeFileSync(root+'/states/index.json',JSON.stringify(states,null,2));await b.close();console.log('DONE',states.length,Object.keys(manifest).length)})().catch(e=>{console.error(e);process.exitCode=1});
